version: '3'
services:
  grafana:
    image: grafana/grafana:9.0.4
    ports:
      - "3000:3000"
    environment:
      GF_LOG_LEVEL: debug
      GF_SECURITY_ADMIN_PASSWORD: yourpasswordhere
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: hadesarchitect-cassandra-datasource
    volumes:
      - /var/lib/grafana
      - ./dist:/var/lib/grafana/plugins/cassandra
  cassandra:
    image: cassandra:4
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
     - ./cassandra-data:/var/lib/cassandra/data:rw